

name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    if: (github.ref_name == 'master' || startsWith(github.ref_name, 'release/') == true)
    steps:
      - name: my-step
        run: echo "Hello World!"
